export enum Page {
  HOME,
  LOGIN,
  CATEGORIES,
  CREATE_CATEGORY,
  EDIT_CATEGORY,
  COLORS,
  CREATE_COLORS,
  EDIT_COLORS,
  BRANDS,
  CREATE_BRAND,
  EDIT_BRAND,
  PARAMETERS,
  CREATE_PARAMETER,
  EDIT_PARAMETER,
  PRODCUCTS,
  CREATE_PRODUCT,
  EDIT_PRODUCT,
  IMAGES,
  CREATE_IMAGE,
  EDIT_IMAGE,
}

export const paths = {
  [Page.HOME]: "/",
  [Page.LOGIN]: "/login",
  [Page.CATEGORIES]: '/categories',
  [Page.CREATE_CATEGORY]: '/categories/create-category',
  [Page.EDIT_CATEGORY]: '/categories/[id]',
  [Page.COLORS]: '/colors',
  [Page.CREATE_COLORS]: '/colors/create-color',
  [Page.EDIT_COLORS]: '/colors/[id]',
  [Page.BRANDS]: '/brands',
  [Page.CREATE_BRAND]: '/brands/create-brand',
  [Page.EDIT_BRAND]: '/brands/[id]',
  [Page.PARAMETERS]: '/parameters',
  [Page.CREATE_PARAMETER]: '/parameters/create-parameter',
  [Page.EDIT_PARAMETER]: '/parameters/[id]',
  [Page.PRODCUCTS]: '/products',
  [Page.CREATE_PRODUCT]: '/products/create-product',
  [Page.EDIT_PRODUCT]: '/products/[id]',
  [Page.IMAGES]: '/images',
  [Page.CREATE_IMAGE]: '/images/create-image',
  [Page.EDIT_IMAGE]: '/images/[id]',
};
