export enum ManageProductFields {
  Name = 'name',
  Price = 'price',
  OldPrice = 'oldPrice',
  wholeSalePrice = 'wholeSalePrice',
  Desc = 'desc',
  ShortDesc = 'shortDesc',
  Keywords = 'keywords',
  Available = 'available',
  Color = 'color',
  Category = 'category',
  Images = 'images',
  Brand = 'brand',
  Tags = 'tags',
  Sizes = 'sizes',
  Url = 'url',
}
